/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
import javax.swing.ImageIcon;
/**
 *
 * @author gusatav
 */
public class telaprinc extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(telaprinc.class.getName());
    ImageIcon imgHappy;
    ImageIcon imgBrabo; 

    /**
     * Creates new form telaprinc
     */
    public telaprinc() {
        imgHappy = new ImageIcon(telaprinc.class.getResource("/jiraiahappy.png"));
        imgBrabo = new ImageIcon(telaprinc.class.getResource("/jiraiabrabo.png"));
        
        
        initComponents();
        lblJiraya.setIcon(imgHappy);
        lblFrase.setText("<html><body style='width: 300px; text-align: center;'>" +
               "Vou concentrar meu chakra e<br>" +
               "pensar em um valor de 1 a 5.<br>" +
               "Vejamos se você lê os movimentos<br>" +
               "de um mestre. Tente a sorte!! " +
               "</body></html>");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtVal = new javax.swing.JSpinner();
        btnPalpite = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        lblFrase = new javax.swing.JLabel();
        lblBalao = new javax.swing.JLabel();
        lblJiraya = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtVal.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        txtVal.setModel(new javax.swing.SpinnerNumberModel(1, 1, 5, 1));
        getContentPane().add(txtVal, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 320, -1, -1));

        btnPalpite.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        btnPalpite.setText("Palpite");
        btnPalpite.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPalpiteActionPerformed(evt);
            }
        });
        getContentPane().add(btnPalpite, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 380, -1, -1));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel1.setText("Valor");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 320, -1, -1));

        lblFrase.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblFrase.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblFrase.setText("Frase");
        getContentPane().add(lblFrase, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 70, 400, 110));

        lblBalao.setIcon(new javax.swing.ImageIcon(getClass().getResource("/balao.png"))); // NOI18N
        lblBalao.setText(" ");
        getContentPane().add(lblBalao, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, -10, -1, -1));

        lblJiraya.setIcon(new javax.swing.ImageIcon(getClass().getResource("/jiraiahappy.png"))); // NOI18N
        getContentPane().add(lblJiraya, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 70, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnPalpiteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPalpiteActionPerformed
        double n = 1 + Math.random() * (6 - 1);
        int valor = (int) n; //sorteio do numero
        
        int num = Integer.parseInt(txtVal.getValue().toString()); //pegando o numero do usuario
        
        String f1 = "<html>Acertou</html>";
        String f2 = "<html>ERROU! Eu estava pesando nesse valor<strong> " + valor + "</html>";
        
        String res = (valor == num)?f1:f2;
        
        lblFrase.setText(res);
        if (valor == num) {
            lblFrase.setText(f1);
            lblJiraya.setIcon(imgBrabo);   // 
        } else {
            lblFrase.setText(f2);
            lblJiraya.setIcon(imgHappy);   // 
        }
        
    }//GEN-LAST:event_btnPalpiteActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new telaprinc().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnPalpite;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel lblBalao;
    private javax.swing.JLabel lblFrase;
    private javax.swing.JLabel lblJiraya;
    private javax.swing.JSpinner txtVal;
    // End of variables declaration//GEN-END:variables
}
